apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-graffiti
  namespace: kube-graffiti
  labels:
    app: kube-graffiti
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - admissionregistration.k8s.io/v1beta1
    resources:
      - MutatingWebhookConfiguration
    verbs:
      - get
      - create
      - delete
