apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: isto-namespace-webhook
  namespace: istio-namespace-webhook
  labels:
    app: istio-namespace-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - admissionregistration.k8s.io/v1beta1
    resources:
      - MutatingWebhookConfiguration
    verbs:
      - get
      - create
      - delete
