apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-graffiti
  namespace: kube-graffiti
  labels:
    app: kube-graffiti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-graffiti
  template:
    metadata:
      labels:
        app: kube-graffiti
    spec:
      serviceAccount: kube-graffiti
      containers:
        - name: kube-graffiti
          image: kube-graffiti:dev
          imagePullPolicy: Never
          env:
            - name: GRAFFITI_LOG_LEVEL
              value: debug
            - name: GRAFFITI_CHECK_EXISTING
              value: "false"
          volumeMounts:
          - name: webhook-certs
            mountPath: /tls
          ports:
            - containerPort: 8443
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
      volumes:
      - name: webhook-certs
        secret:
          secretName: kube-graffiti-certs

