apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kube-graffiti-config
data:
  graffiti-config.yaml: |
    log-level: {{ .Values.loggingLevel }}
    check-existing: {{ .Values.checkExisting }}
    server:
      port: {{ .Values.server.port }}
      namespace: {{ .Release.Namespace }}
      service: {{ include "kube-graffiti.fullname" . }}
      company-domain: {{ .Values.server.companyDomain }}
      ca-cert-path: /tls/ca-cert
      cert-path: /tls/server-cert
      key-path: /tls/server-key
    health-checker:
      port: {{ .Values.healthChecker.port }}
      path: {{ .Values.healthChecker.path }}
    rules:
    - registration:
        name: add-name-label-to-namespaces
        targets:
        - api-groups:
          - ""
          api-versions:
          - v1
          resources:
          - namespaces
        failure-policy: Ignore
      additions:
        labels:
          name: '{{"{{"}} index . "metadata.name" {{"}}"}}'