apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kube-graffiti-config
data:
  graffiti-config.yaml: |
    log-level: {{ .Values.logLevel }}
    check-existing: {{ .Values.checkExisting }}
    health-checker:
{{ toYaml .Values.healthChecker | indent 6 }}
    server:
      port: {{ .Values.server.port }}
      company-domain: {{ .Values.server.companyDomain }}
      namespace: {{ .Release.Namespace }}
      {{ if eq .Values.service.name "" -}}
      service: {{ include "kube-graffiti.fullname" . }}
      {{ else -}}
      service: {{ .Values.service.name }}
      {{ end -}}
      ca-cert-path: /tls/ca-cert
      cert-path: /tls/server-cert
      key-path: /tls/server-key
    rules:
{{ toYaml .Values.rules | indent 6 }}